### ISSUE TITLE
change mouse icon on translation mode

### ISSUE THREAD

**Issue by chrsi** [meinsiedler/zamg-weather-data#3]
Maybe change it to the move cursor symbol.

**Comment by meinsiedler** [comment]
Already tried that, but didn't work well. The new style `cursor: move` has been applied to the element in the HTML code but it wasn't visible while translating. The move cursor stlye was only the visible, when the translation stopped and the mouse wasn't moved any more.

(Maybe this was because of the very frequent update calls for each single minimal mouse movement.)
